version: '3.8'

services:
  notification-service:
    build: .
    ports:
      - "8087:8087"
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - USER_SERVICE_URL=http://user:8084
      - TASK_SERVICE_URL=http://task-service:8082 
    depends_on:
      - redis
    # networks:
    #   - microservices-network

  notification-worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - USER_SERVICE_URL=http://user:8084
      - TASK_SERVICE_URL=http://task-service:8082
    depends_on:
      - redis
    # networks:
    #   - microservices-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
#     networks:
#       - microservices-network

# networks:
#   microservices-network:
#     external: true